config/routes.rb
Rails.application.routes.draw do
  root "deputies#index" 

  resources :uploads

  resources :deputies do
    resources :expenses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deputy.rb
class Deputy < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  paginates_per 10

  validates :name, :cpf, :state, :party_id, presence: true
  validates :cpf, uniqueness: true

  validate :ensure_state_is_rj

  belongs_to :party
  has_many :expenses, dependent: :destroy

  after_save :broadcast!

  def photo
    "https://www.camara.leg.br/internet/deputado/bandep/#{avatar_id}.jpg"
  end

  def self.search(search)
    if search
      joins(:party).where(["deputies.name ILIKE ? OR parties.name ILIKE ?", "%#{search}%", "%#{search}%"])
    else
      all
    end
  end

  def broadcast!
    ActionCable.server.broadcast(
      'deputy_channel', 
      ApplicationController.render(
      partial: 'deputies/deputy',
      locals: { deputy: self }
      )
    )
  end

  private

  def ensure_state_is_rj
    return true if state == 'RJ'

    self.errors.add(:base, 'Invalid State')
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  paginates_per 10

  validates :net_value, :emission_date, :description, :provider_id, :deputy_id, presence: true

  belongs_to :provider
  belongs_to :deputy

  scope :order_by_date, -> { order(emission_date: :asc) }
end

app/models/party.rb
class Party < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :deputies, dependent: :destroy
end

app/models/provider.rb
class Provider < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :expenses
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_one_attached :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deputies_controller.rb
class DeputiesController < ApplicationController
  def index
    @deputies = Deputy.includes(:party).search(params[:search]).page params[:page]
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @deputy = Deputy.friendly.find(params[:deputy_id])
    @expenses = @deputy.expenses.order_by_date.page params[:page]
    @charts = Deputy::Charts.new(@deputy)
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    return redirect_to new_upload_path unless params[:upload][:document].present?
    
    @upload = Upload.create(upload_params)

    ImportExpensesJob.perform_later(@upload.id)

    redirect_to deputies_path, notice: 'Aguarde enquanto carregamos os dados...'
  end

  private

  def upload_params
    params.require(:upload).permit(:document)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def date_formatter(value)
    value&.strftime("%d/%m/%Y")
  end
end

app/views/deputies/_deputy.html.erb
<tr>
  <td class="avatar"><%= image_tag deputy.photo %></td>
  <td><%= deputy.name %></td>
  <td><%= deputy.party.name %></td>
  <td class="table-icon">
    <%= link_to '<i class="far fa-eye"></i>'.html_safe, deputy_expenses_path(deputy) %>
  </td>
</tr>

app/views/deputies/index.html.erb
<div class="container-fluid">
  <header>
    <%= image_tag 'deputy_expense_logo.png' %>
    <%= link_to 'Fazer upload de um novo arquivo', new_upload_path, class: 'link-upload' %>
  </header>

  <%= render 'shared/notifications' %>

  <div class="content">
    <div class="header-table">
      <h1>Lista de deputados - RJ</h1>

      <%= form_with(url:'/deputies', method: 'get', local: true, class: 'search-form') do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag("Pesquisar") %>
        <% if params[:search].present? %>
          <%= link_to 'Limpar pesquisa', deputies_path, class: 'clear-search' %>
        <% end %>
      <% end %>
    </div>

    <table data-channel="deputy" class="table" id='deputy-table'>
      <thead>
        <tr>
          <th scopr="col">FOTO</th>
          <th scope="col">DEPUTADO</th>
          <th scope="col">PARTIDO</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody id="tbody-deputy">
        <% @deputies.each do |deputy| %>
          <%= render partial: 'deputy', locals: { deputy: deputy } %>
        <% end %>
      </tbody>
    </table>

    <% if @deputies.size == 0 %>
      <div class="message-table">
        <p>Nenhum resultado encontrado</p>
      </div>
    <% end %>

    <%= paginate @deputies, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/expenses/index.html.erb
<div class="container-fluid">
  <header>
    <%= image_tag 'deputy_expense_logo.png' %>
    <%= link_to 'Voltar para lista', deputies_path, class: 'link-index' %>
  </header>

  <section>
    <%= image_tag @deputy.photo %>
    <div class="column">
      <h6><%= @deputy.name %></h6>
      <p><%= @deputy.party.name %></p>
    </div>
  </section>

  <div class="content">
    <h1 class="expenses-header-table">Lista de despesas</h1>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">FORNECEDOR</th>
          <th scope="col">DESCRIÇÃO</th>
          <th scope="col">VALOR LÍQUIDO</th>
          <th scope="col">DATA/EMISSÃO</th>
        </tr>
      </thead>

      <tbody>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.provider.name %></td>
            <td><%= expense.description %></td>
            <td><%= number_to_currency(expense.net_value, unit: 'R$') %></td>
            <td><%= date_formatter(expense.emission_date) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @expenses, theme: 'twitter-bootstrap-4' %>   
  </div>

  <div class="content">
    <div class="chart-container">
      <h4>MAIOR VALOR DE DESPESA NO MÊS</h4>
      <%= column_chart @charts.higher_expense_per_month %>
    </div>

    <div class="chart-container">
      <h4>MAIOR VALOR DE DESPESA NO ANO</h4>
      <%= column_chart @charts.higher_expense_per_year %>
    </div>

    <div class="chart-container">
      <h4>TOTAL DE DESPESAS NO MÊS</h4>
      <%= area_chart @charts.total_expense_per_month %>
    </div>

    <div class="chart-container">
      <h4>TOTAL DE DESPESAS NO ANO</h4>
      <%= column_chart @charts.total_expense_per_year %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeputyExpense</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://kit.fontawesome.com/850848e409.js" crossorigin="anonymous"></script>
    
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_notifications.html.erb
<% if notice %>
  <div class="alert alert-secondary" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/uploads/new.html.erb
<div class="container-fluid">
  <header>
    <%= image_tag 'deputy_expense_logo.png' %>
    <%= link_to 'Voltar para lista', deputies_path, class: 'link-index' %>
  </header>

  <div class="div-center">
    <h1>Faça upload do seu arquivo aqui:</h1>

    <div id="file_field">
      <%= form_with model: @upload do |form| %>
        <%= form.file_field :document %>
        <%= form.submit 'Upload', data: { disable_with: 'Enviando...' }, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>